### ISSUE TITLE
Finalize Labels

### ISSUE THREAD

**Issue by jeinglis** [agriculture-capstone/systems#6]
## Review
Brad

**Comment by Parasrah** [comment]
I would recommend using something like [git-labelmaker](https://github.com/himynameisdave/git-labelmaker) to create a json file with the labels shared by all the repos. Then we can actually automate the creation and updating of git labels across the various repos :grin:

**Comment by ExtraGravity** [comment]
My recommendation is to not have any labels. To me the two main uses of the labels is to tell us what stage something is in, or what its about. The pipeline that Zenhub gives us already tells us what stage something is in, and the issue descriptions and names should be enough to tell us what the issue is about.

The other plus side of labels is the colour coding, but I don't think it's worth the duplication of maintenance.

**Comment by jeinglis** [comment]
Epic
Feature
Config
Maintenance

**Comment by mfalthaw** [comment]
Feature 
Epic
Config
Maintenance
Investigation
Test

**Comment by beaesguerra** [comment]
Feature
Epic
Config
Maintenance
Investigation
Test
--- adding these ones that existed already and i thought we missed
assignment
bug
design
discussion

**Comment by beaesguerra** [comment]
updated our labels
